### ISSUE TITLE
【バグ】動的実装のゲーム画面が崩れる

### ISSUE THREAD

**Issue by t--takai** [daisuke85a/bingo#5]
## 概要

画面が崩れてしまっている

たぶん以下の2ファイルを見比べて、間違い探しをする感じだと思われる

- https://github.com/daisuke85a/bingo/blob/develop/dynamic/dist/game.php
- https://github.com/daisuke85a/bingo/blob/develop/static/src/view/game.pug

## 要件の確認

- どのデバイスで正しく見れるようにしたい？

## 対象URL

https://minnya.fun/develop/game.php

以下の画面だとPCサイズは問題なさそう
https://minnya.fun/game/game.html

## スクリーンショット

iPadサイズ（width:768px）

![image01](https://user-images.githubusercontent.com/10617629/53423780-55d90e00-3a25-11e9-820b-dc5769d5e922.png)

PCサイズ（width:1440px）

![image02](https://user-images.githubusercontent.com/10617629/53423783-55d90e00-3a25-11e9-837b-7c8f2d062e92.png)

![image03](https://user-images.githubusercontent.com/10617629/53423782-55d90e00-3a25-11e9-8d76-20e74c508824.png)

**Comment by daisuke85a** [comment]
32f5fdc　で修正しました。
ユーザー名を表示するコードを消去したら治りました。
深い理由はわかってませんごめんなさい。。。
